# docker-compose.yml
version: '3.9'

services:
  go_app:
    image: golang:1.20.3
    container_name: server1
    volumes:
      - ./go:/app
    working_dir: /app
    ports:
      - '80:80'
    command: bash -c "go install && go run ."

  node_app:
    image: node:18.16.0
    container_name: server2
    volumes:
      - ./node:/app
    working_dir: /app
    ports:
      - '81:80'
    command: bash -c "npm install && npm start"
